### ISSUE TITLE
Adjust automatic release workflow. Remove editor from release note.

### ISSUE THREAD

**Issue by vedatbotuk** [vedatbotuk/zigbee-with-esp32h2#123]

**Comment by vedatbotuk** [comment]
```
# Step 7: Create a GitHub release with FIRMWARE_VERSION and VERSION
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version_tag.outputs.TAG }}
          release_name: "Release ${{ steps.version_info.outputs.firmware_version }} - Version ${{ steps.version_info.outputs.version }}"
          body: "Automated release for changes merged into main.\nFirmware Version: ${{ steps.version_info.outputs.firmware_version }}\nVersion Code: ${{ steps.version_info.outputs.version }}"
          draft: false
          prerelease: false
```
